name: d_input
description: Build faster input with default border style
version: 1.4.0
homepage: https://github.com/indratrisnar/d_input

environment:
  sdk: ^3.5.1
  flutter: ">=3.24.1"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  image_picker: ^1.1.2
  file_picker: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
