name: d_input
description: Build faster input with default border style
version: 0.1.4
homepage: https://github.com/indratrisnar/d_input

environment:
  sdk: ^3.5.1
  flutter: ">=3.24.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
